drop table PENCILCASE;

create table PENCILCASE (NAME VARCHAR(255),LENGTH INT, FUNCTION VARCHAR(255),COLOR VARCHAR(255));

insert into PENCILCASE (NAME, LENGTH,FUNCTION, COLOR) values('MITSUBISHI',15, 'PEN','BLACK');
insert into PENCILCASE (NAME, LENGTH,FUNCTION, COLOR) values('GORGEOUS',16, 'RULER','PINK');
insert into PENCILCASE (NAME, LENGTH,FUNCTION, COLOR) values('AIN',6, 'ERASER','BLUE');
insert into PENCILCASE (NAME, LENGTH,FUNCTION, COLOR) values('GOLD',9, 'MECHANICAL PENCIL','YELLOW');
insert into PENCILCASE (NAME, LENGTH,FUNCTION, COLOR) values('BARUNSON',15, 'SHARP','RED');

update PENCILCASE set FUNCTION='SHARP' where COLOR='BLACK&RED';

delete from PENCILCASE where name='GOLD';


