drop table VIEWERRATINGS;

-- [CREATE]
 CREATE TABLE VIEWERRATINGS (NUM int AUTO_INCREMENT, TITLE varchar(255), CHANNEL varchar(255), RATING varchar(255), PRIMARY KEY(NUM));

-- [INSERT]
 INSERT INTO VIEWERRATINGS (TITLE, CHANNEL, RATING) VALUES ('왓다! 장보리', 'MBC', '34.2%');
 INSERT INTO VIEWERRATINGS (TITLE, CHANNEL, RATING) VALUES ('가족끼리 왜 이래', 'KBS2', '27.0%');
 INSERT INTO VIEWERRATINGS (TITLE, CHANNEL, RATING) VALUES ('고양이는 있다', 'KBS1', '22.6%');
 INSERT INTO VIEWERRATINGS (TITLE, CHANNEL, RATING) VALUES ('마마', 'MBC', '19.8%');
 INSERT INTO VIEWERRATINGS (TITLE, CHANNEL, RATING) VALUES ('해피선데이', 'KBS2', '17.0%');
 INSERT INTO VIEWERRATINGS (TITLE, CHANNEL, RATING) VALUES ('KBS 뉴스 9', 'KBS1', '16.1%');
 INSERT INTO VIEWERRATINGS (TITLE, CHANNEL, RATING) VALUES ('청담동 스캔들', 'KBS1', '14.20%');

-- [UPDATE]
 UPDATE VIEWERRATINGS set CHANNEL='SBS' where NUM='7';

-- [DELETE]
 DELETE from VIEWERRATINGS where CHANNEL='KBS1';
