[CREATE]

CREATE TABLE SHOES(
	CODE INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255),
	COLOR VARCHAR(255),
	BRAND VARCHAR(255),
	PRICE INT
);


[INSERT]

INSERT INTO SHOES (CODE, NAME, COLOR, BRAND, PRICE)
    VALUES(0039200, 'ARTNOUVEAU', 'SN.SILVER', 'NUOVO', 59000 );

INSERT INTO SHOES (CODE, NAME, COLOR, BRAND, PRICE)
    VALUES (38678, 'JACK PURCELL LTT OX', 'NAV', 'CONVERSE', 79000);

INSERT INTO SHOES (CODE, NAME, COLOR, BRAND, PRICE)
    VALUES (39764, 'TRINOMIC R698 STREET', 'quarry-marshmallow-black', 'PUMA', 109000);

INSERT INTO SHOES (CODE, NAME, COLOR, BRAND, PRICE)
    VALUES (38866, 'WMNS NIKE FORCE SKY HIGH', '102', 'NIKE', 99000);

INSERT INTO SHOES (CODE, NAME, COLOR, BRAND, PRICE)
    VALUES (39028, 'OLD SKOOL', 'BEIGH/BLACK', 'VANS', 59000);


[UPDATE]

UPDATE SHOES SET CODE=39107, NAME='CORE HI', COLOR='BBK', PRICE=52000 WHERE BRAND='CONVERSE';

update SHOES set CODE=39371, NAME='TIP ZIP', PRICE=62000 where CODE=39107;


[DELETE]

delete from SHOES where code=38866;

